variables:
  DEBIAN_FRONTEND: noninteractive
  NODE_VERSION: 13
  CONTENTFUL_LOCALE: "fr-FR"

.build: &build
  stage: build
  image: ruby:2.6-stretch
  script:
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get install -y nodejs
    - npm install
    - bundle install
    - 'echo url: \"$URL\" >> _config.yml'
    - 'echo ga: $GA >> _config.yml'
    - CONTENTFUL_CONTENT_TYPE_ID="post" OUTPUT_DIR="src/_articles" npm run contentful2md
    - CONTENTFUL_CONTENT_TYPE_ID="tag" OUTPUT_DIR="src/_tags" npm run contentful2md
    - npm run build
    - bundle exec jekyll build -t
  cache:
    paths:
      - node_modules/
    key: "build-$CI_COMMIT_REF_NAME"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA"
    paths:
      - build/
  tags:
    - docker

build_preprod:
  <<: *build
  variables:
    URL: $PREPROD_URL
    GA: "false"
  before_script:
    - mv src/_robots.preprod.txt src/robots.txt

build_prod:
  <<: *build
  variables:
    URL: $PROD_URL
    GA: "true"
  before_script:
    - 'true'
  only:
    - master

deploy_preprod:
  stage: deploy
  dependencies:
    - build_preprod
  image: php:7.3-cli
  environment:
    name: preprod
    url: $PREPROD_URL
  script:
    - curl -LO https://deployer.org/releases/v4.2.1/deployer.phar
    - php deployer.phar deploy preprod
  tags:
    - docker
  only:
    - master

deploy_prod:
  stage: deploy
  dependencies:
    - build_prod
  image: php:7.3-cli
  environment:
    name: prod
    url: $PROD_URL
  script:
    - curl -LO https://deployer.org/releases/v4.2.1/deployer.phar
    - php deployer.phar deploy prod
  tags:
    - docker
  only:
    - master
  when: manual
