variables:
  DEBIAN_FRONTEND: noninteractive
  NODE_VERSION: 9
  PREPROD_URL: https://naddymess.spapp.fr

build_preprod:
  stage: build
  image: ruby:2.4.3-stretch
  script:
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get install -y nodejs
    - npm install
    - bundle install
    - 'echo url: \"$PREPROD_URL\" >> _config.yml'
    - node contentful.js
    - ./node_modules/.bin/gulp --env production
  cache:
    paths:
      - node_modules/
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA"
    paths:
      - build/
  tags:
    - docker

deploy_preprod:
  stage: deploy
  dependencies:
    - build_preprod
  image: php:7.2-cli
  environment:
    name: prod
    url: $PREPROD_URL
  script:
    - curl -LO https://deployer.org/releases/v4.2.1/deployer.phar
    - php deployer.phar deploy preprod
  tags:
    - docker
  only:
    - master
