variables:
  DEBIAN_FRONTEND: noninteractive
  NODE_VERSION: 9
  PREPROD_URL: https://naddymess.spapp.fr
  PROD_URL: https://www.naddymess.fr

.build: &build
  stage: build
  image: ruby:2.4.3-stretch
  before_script:
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get install -y nodejs
    - npm install
    - bundle install
    - 'echo url: \"$URL\" >> _config.yml'
    - 'echo ga: $GA >> _config.yml'
    - node contentful.js
    - npm run build
    - bundle exec jekyll build -t
  cache:
    paths:
      - node_modules/
    key: "build-$CI_COMMIT_REF_NAME"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA"
    paths:
      - build/
  tags:
    - docker

build_preprod:
  <<: *build
  variables:
    URL: $PREPROD_URL
    GA: "false"
  script:
    - ls build/

build_prod:
  <<: *build
  variables:
    URL: $PROD_URL
    GA: "true"
  script:
    - ls build/
  only:
    - master

deploy_preprod:
  stage: deploy
  dependencies:
    - build_preprod
  image: php:7.2-cli
  environment:
    name: preprod
    url: $PREPROD_URL
  script:
    - curl -LO https://deployer.org/releases/v4.2.1/deployer.phar
    - php deployer.phar deploy preprod
  tags:
    - docker
  only:
    - master

deploy_prod:
  stage: deploy
  dependencies:
    - build_prod
  image: php:7.2-cli
  environment:
    name: prod
    url: $PROD_URL
  script:
    - curl -LO https://deployer.org/releases/v4.2.1/deployer.phar
    - php deployer.phar deploy prod
  tags:
    - docker
  only:
    - master
  when: manual
