variables:
  DEBIAN_FRONTEND: noninteractive
  NODE_VERSION: "18"
  CONTENTFUL_LOCALE: "fr-FR"

.build: &build
  stage: build
  image: ruby:3.0
  script:
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get install -y nodejs
    - npm ci
    - bundle install
    - 'echo url: \"$URL\" >> _config.yml'
    - 'echo ga: $GA >> _config.yml'
    - CONTENTFUL_CONTENT_TYPE_ID="post" OUTPUT_DIR="src/_articles" npm run contentful2md
    - CONTENTFUL_CONTENT_TYPE_ID="tag" OUTPUT_DIR="src/_tags" npm run contentful2md
    - npm run build
    - bundle exec jekyll build -t
  cache:
    paths:
      - node_modules/
    key: "build-$CI_COMMIT_REF_NAME"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHA"
    paths:
      - build/

# build_preprod:
#   <<: *build
#   variables:
#     URL: $PREPROD_URL
#     GA: "false"
#   before_script:
#     - mv src/_robots.preprod.txt src/robots.txt

build_prod:
  <<: *build
  variables:
    URL: $PROD_URL
    GA: "true"
  before_script:
    - 'true'
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - build_prod
  image: alpine
  environment:
    name: prod
    url: $PROD_URL
  script:
    - mv build/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
  when: manual
